CREATE TABLE short_link (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code  VARCHAR(16)   NOT NULL,
    long_url    VARCHAR(2048) NOT NULL,
    created_at  TIMESTAMP     NOT NULL,
    expires_at  TIMESTAMP,
    active      BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX ux_short_link_short_code ON short_link (short_code);