CREATE TABLE click_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code     VARCHAR(16)  NOT NULL,
    clicked_at     TIMESTAMP    NOT NULL,
    referrer       VARCHAR(512),
    user_agent     VARCHAR(512),
    client_ip_hash VARCHAR(64)
);

CREATE INDEX ix_click_event_code_time ON click_event (short_code, clicked_at);